<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class BarangmasukModel extends CI_Model
{

    public $table = 'barangMasuk';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('idUser', $q);
	$this->db->or_like('namaSuplier', $q);
	$this->db->or_like('idProduk', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('jumlah', $q);
	$this->db->or_like('modal', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('idUser', $q);
	$this->db->or_like('namaSuplier', $q);
	$this->db->or_like('idProduk', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('jumlah', $q);
	$this->db->or_like('modal', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function cari_nama($produk){
        $this->db->like('nama', $produk , 'both');
        $this->db->order_by('nama', 'ASC');
        $this->db->limit(10);
        return $this->db->get('stok')->result();
    }

    function search_blog($title){
        $this->db->like('blog_title', $title , 'both');
        $this->db->order_by('blog_title', 'ASC');
        $this->db->limit(10);
        return $this->db->get('blog')->result();
    }

}

/* End of file BarangmasukModel.php */
/* Location: ./application/models/BarangmasukModel.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-01-17 21:26:12 */
/* http://harviacode.com */