<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Transaksi_model extends CI_Model
{

    public $table = 'transaction';
    public $id = 'id_transaction';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_transaction', $q);
	$this->db->or_like('transaction_date', $q);
	$this->db->or_like('transaction_type', $q);
	$this->db->or_like('id_user', $q);
	$this->db->or_like('transaction_customer', $q);
	$this->db->or_like('id_product', $q);
	$this->db->or_like('stock_price', $q);
	$this->db->or_like('product_price', $q);
	$this->db->or_like('transaction_qty', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_transaction', $q);
	$this->db->or_like('transaction_date', $q);
	$this->db->or_like('transaction_type', $q);
	$this->db->or_like('id_user', $q);
	$this->db->or_like('transaction_customer', $q);
	$this->db->or_like('id_product', $q);
	$this->db->or_like('stock_price', $q);
	$this->db->or_like('product_price', $q);
	$this->db->or_like('transaction_qty', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Transaksi_model.php */
/* Location: ./application/models/Transaksi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-01-07 15:57:09 */
/* http://harviacode.com */